net.sf.jasperreports.xml.validation=false
net.sf.jasperreports.compiler.xml.validation=false
net.sf.jasperreports.compiler.xml.parser.cache.schemas=false
net.sf.jasperreports.compiler.keep.java.file=false
